# *** This Dockefile is generated by KloverCloud. You can modify it based on your application requirements *** #
FROM klovercloud/nginx-python:v1.0.0

RUN apk update && apk add postgresql-dev gcc python3-dev libressl-dev musl-dev libffi-dev
RUN apk add --no-cache jpeg-dev zlib-dev
RUN apk add --no-cache --virtual .build-deps build-base linux-headers
RUN apk add --no-cache bash

ENV APP_HOME /home/klovercloud/app

ENV PYTHONUNBUFFERED 1

RUN adduser --disabled-password --gecos '' --shell "/sbin/nologin" --uid "1000" klovercloud

WORKDIR $APP_HOME

RUN mkdir static

COPY --chown=klovercloud:klovercloud ./src .

# Get pip to download and install requirements:
RUN pip install --no-cache-dir -r requirements.txt

RUN python manage.py collectstatic --no-input

## Copy our default nginx config
COPY ./nginx/config/default.conf /etc/nginx/conf.d/

EXPOSE 8080

RUN chown -R klovercloud:klovercloud $APP_HOME && chmod -R 755 $APP_HOME && \
        chown -R klovercloud:klovercloud /var/cache/nginx && \
        chown -R klovercloud:klovercloud /var/log/nginx && \
        chown -R klovercloud:klovercloud /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
        chown -R klovercloud:klovercloud /var/run/nginx.pid

COPY run.sh $APP_HOME/run.sh
RUN chmod +x $APP_HOME/run.sh

USER klovercloud

ENTRYPOINT ["bash", "/home/klovercloud/app/run.sh"]
